name: nebuchadnezzar
description: "Matrix chat application"

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.10.0 <4.0.0"

dependencies:
  adaptive_dialog: ^2.6.0
  animated_emoji: ^3.2.1
  async: ^2.13.0
  audio_metadata_reader: ^1.4.2
  audio_service: ^0.18.18
  audio_service_mpris:
    git:
      url: https://github.com/Feichtmeier/audio-service-mpris
      ref: ad6f743b73e320670449026fa1852d9978438bb9
  basic_utils: ^5.8.2
  cached_network_image: ^3.4.1
  collection: ^1.19.1
  cross_file: ^0.3.5+2
  cupertino_icons: ^1.0.8
  dio: ^5.9.1
  emoji_picker_flutter: ^4.4.0
  file: ^7.0.1
  file_picker: ^10.3.10
  file_selector: ^1.1.0
  file_selector_linux: ^0.9.4
  flutter:
    sdk: flutter
  flutter_cache_manager: ^3.4.1
  flutter_highlighter: ^0.1.1
  flutter_html: ^3.0.0
  flutter_it: ^2.1.2
  flutter_linkify: ^6.0.0
  flutter_localizations:
    sdk: flutter
  flutter_map: ^8.2.2
  flutter_secure_storage: ^10.0.0
  flutter_svg: ^2.2.3
  flutter_vodozemac: ^0.5.0
  flutter_web_auth_2: ^5.0.1
  future_loading_dialog: ^0.3.0
  handy_window: ^0.4.0
  html: ^0.15.6
  intl: ^0.20.2
  latlong2: ^0.9.1
  linkify: ^5.0.0
  liquid_progress_indicator_v2: ^0.5.0
  local_notifier: ^0.1.6
  matrix: ^6.1.1
  media_kit:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./media_kit
  media_kit_libs_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/universal/media_kit_libs_video
  media_kit_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./media_kit_video
  mesh: ^0.5.0
  mime: ^2.0.0
  opus_caf_converter_dart: ^1.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  photo_view: ^0.15.0
  radio_browser_api: ^2.0.0+1
  safe_change_notifier: ^0.4.0+1
  scroll_to_index: ^3.0.1
  shared_preferences: ^2.5.4
  slugify: ^2.0.0
  sqflite: ^2.4.2
  sqflite_common_ffi: ^2.3.7+1
  sqlcipher_flutter_libs: ^0.6.8
  super_clipboard: ^0.9.1
  super_drag_and_drop: ^0.9.1
  synchronized: ^3.4.0
  system_theme: ^3.2.0
  tabler_icons: ^2.5.0+1
  universal_html: ^2.3.0
  url_launcher: ^6.3.2
  video_compress: ^3.1.4
  window_manager: ^0.5.1
  xdg_directories: ^1.1.0
  xdg_icons: ^0.1.2
  yaru: ^9.0.1

dev_dependencies:
  build_runner: ^2.11.1
  flutter_launcher_icons: ^0.14.4
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

dependency_overrides:
  media_kit_libs_android_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/android/media_kit_libs_android_video
  media_kit_libs_ios_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/ios/media_kit_libs_ios_video
  media_kit_libs_linux:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/linux/media_kit_libs_linux
  media_kit_libs_macos_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/macos/media_kit_libs_macos_video
  media_kit_libs_ohos:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/ohos/media_kit_libs_ohos
  media_kit_libs_windows_video:
    git:
      url: https://github.com/Predidit/media-kit.git
      ref: 7d1e3f8116abce740bdf83dc5e85f37e89436db5
      path: ./libs/windows/media_kit_libs_windows_video

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/vodozemac/

flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/nebuchadnezzar.png"
  macos:
    generate: true
    image_path: "assets/nebuchadnezzar.png"
  web:
    generate: true
    image_path: "assets/nebuchadnezzar.png"
    background_color: "#ccc"
    theme_color: "#ccc"

assets:
  - "assets/nebuchadnezzar.png"
